### PR TITLE
add cmake to Dockerfile

### PR DESCRIPTION
**Pull request by kaspar030**
relic needs it...

### CODE REVIEW

**Comment by gebart** [comment]
ACK

**Comment by kaspar030** [comment]
And go!

**Comment by kaspar030** [comment]
@gebart How does an image here end up as being the one that gets pulled if I do "docker pull riot/riotbuild"?

**Comment by gebart** [comment]
There's a hook to the Docker hub so it gets rebuilt automatically. While you're working with the containers, could you take a look at #11?

**Pull request merged**
