### PR TITLE
llvm: Bump to LLVM version 10

### PR DESCRIPTION
**Pull request by bergzand**
Bump our LLVM/Clang to version 10. Explicitly adding the version number so that we don't accidentally start to pull in v11 when bionic-updates bumps the available version.

### CODE REVIEW

**Comment by kaspar030** [comment]
travis failed on the llvm tests.

**Comment by bergzand** [comment]
`/usr/bin/clang` is not provided by the `clang-10` package.

**Comment by benpicco** [comment]
Do we need to run `update-alternatives` or can we just create the symlink ourself?

**Comment by bergzand** [comment]
> Do we need to run `update-alternatives` or can we just create the symlink ourself?

I think we have to create it manually. `/usr/bin/{llvm,clang}` are part of the `llvm` and `clang` package I think.

**Comment by bergzand** [comment]
I've added a bit of logic to add symlinks based on already existing symlinks in /usr/bin pointing to /usr/lib/llvm-10 and recreate them without the version suffix. This should override all the llvm/clang symlinks to use version 10.

**Comment by bergzand** [comment]
This is ready for review:

```
koen@morgen ~/dev/riotdocker $ docker run --rm -i -t -u $UID  riotbuild:custom /usr/bin/clang --version
clang version 10.0.0-4ubuntu1~18.04.2 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by bergzand** [comment]
A different approach is to download the binary releases from the LLVM project, verify them and install them manually in `/usr/local/bin`. That allows a bit more freedom in that we're not restricted to what Ubuntu provides in their updates repo.

**Comment by kaspar030** [comment]
Lgtm. Is there no update-alternatives for llvm?

**Comment by bergzand** [comment]
> Is there no update-alternatives for llvm?

I would prefer to use that over the manual creation of the symlinks. Please prove me wrong, but I could not find it. I did find a few ways to manually add entries to the update-alternatives by specifying the link name, target and the priority, but that doesn't really help here.

**Comment by bergzand** [comment]
Can I squash this?

**Comment by kaspar030** [comment]
please squash!

**Review by kaspar030 — APPROVED** [review]
ACK.
Basic compilation is asserted by travis, change LGTM.

**Pull request merged**
