### PR TITLE
.github/workflows/build.yml: bump verison to 2022.04

### PR DESCRIPTION
**Pull request by benpicco**

### CODE REVIEW

**Review by kaspar030 — APPROVED** [review]
ACK.

**Comment by benpicco** [comment]
CI does not like the change though :(

> fatal: unsafe repository ('/data/riotbuild' is owned by someone else)
17

**Comment by kaspar030** [comment]
same here: https://github.com/RIOT-OS/riotdocker/pull/191

must be some upstream change

**Comment by kaspar030** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Pull request merged**
