### PR TITLE
bors: require 1 review (approval)

### PR DESCRIPTION
**Pull request by kaspar030**
Let's try using bors to require ACKs.

### CODE REVIEW

**Review by miri64 — DISMISSED** [review]
ACK

bors merge

**Comment by miri64** [comment]
bors merge

**Comment by kaspar030** [comment]
> Testing

so dismissing a review while this is in progress does not cancel.

**Comment by miri64** [comment]
I did not expect that, but I wanted to test how it will react when the the review is dismissed. Will it merge regardless? Currently it does not look like it. And how does it react to that the branch is out of date?

**Comment by miri64** [comment]
> > Will it merge regardless? Currently it does not look like it.
> 
> I think it will, the build is still running.

Ok. It will. I guess we need to look out for this then.

**Comment by kaspar030** [comment]
> > > Will it merge regardless? Currently it does not look like it.
> > 
> > 
> > I think it will, the build is still running.
> 
> Ok. It will. I guess we need to look out for this then.

yeah. dismiss and say "bors cancel".

**Comment by kaspar030** [comment]
now I'd like to see the batching in action, but there's not enough action in this repo. :grin:

**Comment by kaspar030** [comment]
oh, nice, the master build failed on this: "'Connection to pypi.python.org timed out. (connect timeout=15)'))"

**Pull request merged**
