### PR TITLE
Dockerfile: update picolibc to 1.5.1

### PR DESCRIPTION
**Pull request by benpicco**
This should fix builds with clang.

~~https://github.com/picolibc/picolibc/releases/tag/1.4.7~~

https://github.com/picolibc/picolibc/releases/tag/1.5.1

### CODE REVIEW

**Comment by kaspar030** [comment]
travis cannot build picolibc: `sh: 0: Can't open ../do-esp32-configure`

**Comment by benpicco** [comment]
Ah turns out the scripts were moved.

**Comment by kaspar030** [comment]
```
../meson.build:35:0: ERROR: Unknown compiler(s): [['riscv64-unknown-elf-gcc']]

The follow exceptions were encountered:

Running "riscv64-unknown-elf-gcc --version" gave "[Errno 2] No such file or directory: 'riscv64-unknown-elf-gcc': 'riscv64-unknown-elf-gcc'"

**Comment by benpicco** [comment]
Yea I thought I could do away with our custom `cross-riscv-none-embed.txt` while I'm at it, but I guess I was a bit too eager.

**Comment by maribu** [comment]
With https://github.com/RIOT-OS/riotdocker/pull/116 merged this should no longer be needed. If anyone disagrees, please just re-open :)

**Pull request closed without merging**
