### PR TITLE
Move to Ubuntu 16.04 base image

### PR DESCRIPTION
**Pull request by gebart**
This PR changes the wily (15.10) base image to xenial (16.04) and adapts the Cortex-M PPA accordingly.

### CODE REVIEW

**Comment by miri64** [comment]
(untested) ACK

**Comment by gebart** [comment]
Hmm, we might need to postpone this until https://github.com/RIOT-OS/RIOT/pull/5601 is merged because of more recent toolchain in the new Ubuntu release.

**Comment by miri64** [comment]
kk

**Comment by miri64** [comment]
RIOT-OS/RIOT#5601 was merged, so go?

**Comment by gebart** [comment]
yes, let's

**Pull request merged**
