### PR TITLE
bump workflow RIOT_BRANCH / VERSION_TAG to `2022.07-branch` / `2022.10`

### PR DESCRIPTION
**Pull request by kaspar030**

### CODE REVIEW

**Comment by kaspar030** [comment]
I forgot about this, it had failed the build back then due to an unrelated error. let's see now.

**Comment by kaspar030** [comment]
hm, does the release branch actually change the riotdocker container to a tagged one?

**Comment by kaspar030** [comment]
hm,

```
Running "./dist/tools/doccheck/check.sh" x
Command output:

	ERROR: Doxygen generates the following warnings:
	sys/include/net/gcoap/fileserver.h:20: warning: End of list marker found without any preceding list items
	sys/include/net/gcoap/fileserver.h:24: warning: End of list marker found without any preceding list items
```

**Review by maribu — APPROVED** [review]

**Comment by maribu** [comment]
bors merge

**Pull request merged**
