### PR TITLE
add travis automatic build on PRs

### PR DESCRIPTION
**Pull request by aabadie**
Not sure if it's worth it but I think it would be great to have some kind of build check of the Docker image when one introduces new packages, etc

This PR just add a travis configuration file that just triggers a new build of the Docker image. If accepted, we'll have to setup the travis integration.

~We could even publish new images automatically on successful builds (only from master branch of course).~

### CODE REVIEW

**Comment by kaspar030** [comment]
> We could even publish new images automatically on successful builds (only from master branch of course).

Where do you want to publish them?

**Comment by aabadie** [comment]
> Where do you want to publish them?

on [dockerhub](https://hub.docker.com/r/riot/riotbuild/)

**Comment by aabadie** [comment]
Well, ok docker hub does that for you...

**Comment by kaspar030** [comment]
>> Where do you want to publish them?
> 
> on dockerhub

That already happens automatically on every push to master.

**Comment by aabadie** [comment]
Then, let's leave this PR like this.

**Comment by kaspar030** [comment]
ACK. can you set up travis? It could maybe already test this PR?

**Comment by aabadie** [comment]
> can you set up travis?

I can't because I'm missing rights to do that on the RIOT organisation I think.

**Comment by aabadie** [comment]
@kaspar030, something preventing this from being merged ?

**Comment by aabadie** [comment]
@kaspar030, I still can't activate Travis for this repo: https://travis-ci.org/profile/RIOT-OS. Can you do it yourself ?

**Comment by kaspar030** [comment]
> Can you do it yourself ?

Can you try again?

**Comment by kaspar030** [comment]
> something preventing this from being merged ?

need to have travis check this PR in order to merge. If something is wrong with the travis file, all PR builds would fail, right?

**Comment by aabadie** [comment]
ok, it works @kaspar030, thanks!

**Comment by aabadie** [comment]
The travis file should work, I tested it on my own fork

**Comment by kaspar030** [comment]
Nice! ACK.

**Pull request merged**
