### PR TITLE
Dockerfile: add vera++

### PR DESCRIPTION
**Pull request by leandrolanzieri**
This adds [Vera++](https://bitbucket.org/verateam/vera/wiki/Introduction) to the installation. The CI script to run the check can be found in RIOT-OS/RIOT#9778.

### CODE REVIEW

**Comment by leandrolanzieri** [comment]
Rebased!

**Comment by cladmi** [comment]
This is currently adding almost `500MB` to the image, which is huge for `vera++`, `3.51GB` to `3.99GB`.

**Comment by gebart** [comment]
Are there no binary packages available?

**Comment by miri64** [comment]
Yes there is https://packages.ubuntu.com/de/xenial/vera++

**Comment by leandrolanzieri** [comment]
Using the package now it's `3.52GB`

**Comment by jia200x** [comment]
Vera++ works OK in with this PR but unfortunately RIOT-OS/RIOT#9778 uses the new format (v1.3.0). This PR adds Vera++ 1.2.1.
The vera++ version is the same in Ubuntu Bionic, so updating Ubuntu won't solve the issue.

Then RIOT-OS/RIOT#9778 has to be updated to the v1.2.1 format (unlikely for this Release).

**Comment by jia200x** [comment]
@cladmi or @gebart could you re-review? :)

**Comment by cladmi** [comment]
I cannot run the testing procedure from #9778 if it is not compatible with `1.2.1`.

**Comment by jia200x** [comment]
> I cannot run the testing procedure from #9778 if it is not compatible with 1.2.1.

But this PR is only adding the pkg. It can be tested verifying the image builds correctly and running `vera++ --version`

**Comment by jia200x** [comment]
We need this to proceed with https://github.com/RIOT-OS/RIOT/pull/9778. Can someone give it a look?

**Comment by smlng** [comment]
please rebase

**Comment by leandrolanzieri** [comment]
@smlng rebased

**Comment by jia200x** [comment]
ping @kaspar030

**Comment by kaspar030** [comment]
No objections, IMO this is good to go. BUT we should wait until after release before changing riotdocker.

**Comment by kaspar030** [comment]
please rebase!

**Comment by leandrolanzieri** [comment]
Rebased and CI is green!

**Comment by miri64** [comment]
Then let's go.

**Pull request merged**
