### PR TITLE
add flake8 dependency

### PR DESCRIPTION
**Pull request by aabadie**
Required for https://github.com/RIOT-OS/RIOT/pull/8078

### CODE REVIEW

**Comment by aabadie** [comment]
I looked for one but didn't find. I'll double check because now I'm not sure anymore..

**Comment by smlng** [comment]
python-flake8 from what I googled, but I guess its also fine to use pip, or not?

**Comment by gebart** [comment]
I think pip is fine. I'm guessing that the package python-flake8 is for python 2.7, but I if it follows the naming conventions among the other Ubuntu packages.

**Comment by kaspar030** [comment]
I've got an 16.04 box that offers both python-flake8 and python3-flake8.

The advantage of not using pip (apart from performance reasons) is that canonical takes care of the updating, while when using pip, the docker container becomes less reproducible.

IMO if there's a package, use it, so please change to use python3-flake8

**Comment by aabadie** [comment]
Indeed python3-flake8 exists (just checked as well). I'll change that.

**Comment by aabadie** [comment]
Done

**Comment by kaspar030** [comment]
&go, I'll update the murdock container.

**Comment by cgundogan** [comment]
>I'll update the murdock container.

wait a sec please

**Comment by kaspar030** [comment]
> wait a sec please

ok. sth wrong?

**Comment by cgundogan** [comment]
>ok. sth wrong?

Nope. I'm just about to provide a PR for cmake version >=3.7, because I need that for https://github.com/RIOT-OS/RIOT/issues/7713
I figured it's easier for you to update all murdock instances only once (:

**Comment by cgundogan** [comment]
I meant https://github.com/RIOT-OS/RIOT/pull/7437

**Pull request merged**
